# Generated by Django 4.2 on 2024-11-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachment',
            table='Attachment',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='Chapter',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='logging',
            table='Logging',
        ),
        migrations.AlterModelTable(
            name='muxdata',
            table='MuxData',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='Purchase',
        ),
        migrations.AlterModelTable(
            name='stripecustomer',
            table='StripeCustomer',
        ),
        migrations.AlterModelTable(
            name='userprogress',
            table='UserProgress',
        ),
    ]
