FROM python:3.12-alpine

WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=your_project.settings

RUN python manage.py collectstatic --noinput
RUN python manage.py migrate --noinput

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "lms_api.wsgi:application"]
